// Database types (will be auto-generated by Prisma)
export type * from '@prisma/client'

// API Response types
export interface ApiResponse<T = any> {
  success: boolean
  data?: T
  error?: string
  message?: string
}

// Error types
export interface ApiError {
  message: string
  code?: string
  statusCode?: number
}
